const FLAGS: Record<string, string> = {
  // CONMEBOL
  argentina: "🇦🇷",
  bolivia: "🇧🇴",
  brazil: "🇧🇷",
  chile: "🇨🇱",
  colombia: "🇨🇴",
  ecuador: "🇪🇨",
  paraguay: "🇵🇾",
  peru: "🇵🇪",
  uruguay: "🇺🇾",
  venezuela: "🇻🇪",
  // CONCACAF
  canada: "🇨🇦",
  "costa rica": "🇨🇷",
  costa: "🇨🇷",
  cuba: "🇨🇺",
  curacao: "🇨🇼",
  "el salvador": "🇸🇻",
  guatemala: "🇬🇹",
  haiti: "🇭🇹",
  honduras: "🇭🇳",
  jamaica: "🇯🇲",
  mexico: "🇲🇽",
  panama: "🇵🇦",
  "trinidad and tobago": "🇹🇹",
  trinidad: "🇹🇹",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  // UEFA
  albania: "🇦🇱",
  austria: "🇦🇹",
  belgium: "🇧🇪",
  "bosnia and herzegovina": "🇧🇦",
  bosnia: "🇧🇦",
  bulgaria: "🇧🇬",
  croatia: "🇭🇷",
  "czech republic": "🇨🇿",
  czechia: "🇨🇿",
  denmark: "🇩🇰",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  finland: "🇫🇮",
  france: "🇫🇷",
  germany: "🇩🇪",
  greece: "🇬🇷",
  hungary: "🇭🇺",
  iceland: "🇮🇸",
  ireland: "🇮🇪",
  "republic of ireland": "🇮🇪",
  italy: "🇮🇹",
  "north macedonia": "🇲🇰",
  netherlands: "🇳🇱",
  norway: "🇳🇴",
  poland: "🇵🇱",
  portugal: "🇵🇹",
  romania: "🇷🇴",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  serbia: "🇷🇸",
  slovakia: "🇸🇰",
  slovenia: "🇸🇮",
  spain: "🇪🇸",
  sweden: "🇸🇪",
  switzerland: "🇨🇭",
  turkey: "🇹🇷",
  ukraine: "🇺🇦",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  // CAF
  algeria: "🇩🇿",
  cameroon: "🇨🇲",
  "dr congo": "🇨🇩",
  "democratic republic of congo": "🇨🇩",
  drc: "🇨🇩",
  egypt: "🇪🇬",
  ghana: "🇬🇭",
  "ivory coast": "🇨🇮",
  "cote d'ivoire": "🇨🇮",
  "cote divoire": "🇨🇮",
  mali: "🇲🇱",
  morocco: "🇲🇦",
  nigeria: "🇳🇬",
  senegal: "🇸🇳",
  "south africa": "🇿🇦",
  tanzania: "🇹🇿",
  tunisia: "🇹🇳",
  zambia: "🇿🇲",
  // AFC
  australia: "🇦🇺",
  bahrain: "🇧🇭",
  china: "🇨🇳",
  indonesia: "🇮🇩",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  japan: "🇯🇵",
  jordan: "🇯🇴",
  korea: "🇰🇷",
  "south korea": "🇰🇷",
  "north korea": "🇰🇵",
  oman: "🇴🇲",
  qatar: "🇶🇦",
  "saudi arabia": "🇸🇦",
  saudi: "🇸🇦",
  uzbekistan: "🇺🇿",
  // OFC
  "new zealand": "🇳🇿",
  "new caledonia": "🇳🇨",
  // Faltantes 2026 (clasificados y repechaje)
  "cape verde": "🇨🇻",
  suriname: "🇸🇷",
  kosovo: "🇽🇰",
  uae: "🇦🇪",
  "united arab emirates": "🇦🇪",
  palestine: "🇵🇸",
  lebanon: "🇱🇧",
  syria: "🇸🇾",
  kuwait: "🇰🇼",
  thailand: "🇹🇭",
  vietnam: "🇻🇳",
  gabon: "🇬🇦",
  libya: "🇱🇾",
  sudan: "🇸🇩",
  togo: "🇹🇬",
  uganda: "🇺🇬",
  zimbabwe: "🇿🇼",
  "burkina faso": "🇧🇫",
  benin: "🇧🇯",
  guinea: "🇬🇳",
  "equatorial guinea": "🇬🇶",
  mozambique: "🇲🇿",
  namibia: "🇳🇦",
  angola: "🇦🇴",
  madagascar: "🇲🇬",
  "dominican republic": "🇩🇴",
  nicaragua: "🇳🇮",
  // Alias en español (las claves se buscan sin acentos y en minúsculas)
  brasil: "🇧🇷",
  curazao: "🇨🇼",
  "estados unidos": "🇺🇸",
  "trinidad y tobago": "🇹🇹",
  "republica dominicana": "🇩🇴",
  belgica: "🇧🇪",
  "bosnia y herzegovina": "🇧🇦",
  croacia: "🇭🇷",
  "republica checa": "🇨🇿",
  chequia: "🇨🇿",
  dinamarca: "🇩🇰",
  inglaterra: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  finlandia: "🇫🇮",
  francia: "🇫🇷",
  alemania: "🇩🇪",
  grecia: "🇬🇷",
  hungria: "🇭🇺",
  islandia: "🇮🇸",
  irlanda: "🇮🇪",
  italia: "🇮🇹",
  "macedonia del norte": "🇲🇰",
  "paises bajos": "🇳🇱",
  noruega: "🇳🇴",
  polonia: "🇵🇱",
  rumania: "🇷🇴",
  escocia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  eslovaquia: "🇸🇰",
  eslovenia: "🇸🇮",
  espana: "🇪🇸",
  suecia: "🇸🇪",
  suiza: "🇨🇭",
  turquia: "🇹🇷",
  ucrania: "🇺🇦",
  gales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  argelia: "🇩🇿",
  camerun: "🇨🇲",
  "cabo verde": "🇨🇻",
  "rd del congo": "🇨🇩",
  egipto: "🇪🇬",
  "costa de marfil": "🇨🇮",
  marruecos: "🇲🇦",
  sudafrica: "🇿🇦",
  tunez: "🇹🇳",
  libia: "🇱🇾",
  zimbabue: "🇿🇼",
  "guinea ecuatorial": "🇬🇶",
  barein: "🇧🇭",
  japon: "🇯🇵",
  jordania: "🇯🇴",
  "corea del sur": "🇰🇷",
  "corea del norte": "🇰🇵",
  irak: "🇮🇶",
  "arabia saudita": "🇸🇦",
  catar: "🇶🇦",
  "emiratos arabes unidos": "🇦🇪",
  palestina: "🇵🇸",
  libano: "🇱🇧",
  siria: "🇸🇾",
  tailandia: "🇹🇭",
  "nueva zelanda": "🇳🇿",
  "nueva caledonia": "🇳🇨",
  surinam: "🇸🇷"
};

export function teamFlagEmoji(teamName?: string | null) {
  const value = normalize(teamName);
  if (
    !value ||
    value.includes("winner") || value.includes("runner") || value.includes("third") || value.includes("match") ||
    value.includes("ganador") || value.includes("perdedor") || value.includes("partido") || value.includes("grupo") || value.includes("group ")
  ) return "🏆";
  const direct = FLAGS[value];
  if (direct) return direct;
  const partial = Object.entries(FLAGS).find(([key]) => value.includes(key));
  return partial?.[1] ?? "⚽";
}

function normalize(value?: string | null) {
  return String(value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toLowerCase();
}
